development:
  clients:
    default:
      uri: mongodb://localhost:27017/marketplace?readPreference=primary&appname=MongoDB%20Compass%20Community&ssl=false
      options:
        server_selection_timeout: 5
production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        connect_timeout: 15